[package]
name = "paulx-escrow"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.0"
thiserror = "1.0.24"
spl-token = {version = "6.0.0", features = ["no-entrypoint"]}
arrayref = "0.3.6"


[lib]
crate-type = ["cdylib", "lib"]
